config/routes.rb
Tesoureiro::Application.routes.draw do
  resources :caixas

	resources :transacoes
	
	root to: 'transacoes#index'

end

app/models/caixa.rb
class Caixa < ActiveRecord::Base
	has_many :transacoes
	
	validates :nome, presence: true
	
	def saldo(em=Date.today, params={})
		trns = self.transacoes.where(['data <= ?', em])
		trns = trns.realizadas unless params[:previsto]
		return trns.sum(:valor)
	end
end

app/models/transacao.rb
# encoding: UTF-8

class Transacao < ActiveRecord::Base
	
	belongs_to :caixa
	
	scope :realizadas, where(realizada: true)
	scope :previstas, where(realizada: false)
	before_validation :valor_padrao_realizada
	validates :data, :descricao, :valor, :caixa_id, presence: true
	validate :valida_se_o_valor_eh_zero
	validate :valida_se_o_caixa_existe
	
	def prevista?
		!realizada
	end	
	
	usar_como_dinheiro :valor
	
	def mes_ano
		data.to_s(:mes_ano) if data
	end
		
	private
	
	def valor_padrao_realizada
		self.realizada = false if self.realizada.nil?
	end
	def valida_se_o_valor_eh_zero
		return if self.valor.nil?
		self.errors.add(:valor, 'Não pode ser 0') if self.valor.zero?
	end
	
	def valida_se_o_caixa_existe
		return unless self.caixa_id
		self.errors.add(:caixa_id, "Não existe") unless self.caixa
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/caixas_controller.rb
class CaixasController < ApplicationController
  # GET /caixas
  # GET /caixas.json
  def index
    @caixas = Caixa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @caixas }
    end
  end

  # GET /caixas/1
  # GET /caixas/1.json
  def show
    @caixa = Caixa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @caixa }
    end
  end

  # GET /caixas/new
  # GET /caixas/new.json
  def new
    @caixa = Caixa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @caixa }
    end
  end

  # GET /caixas/1/edit
  def edit
    @caixa = Caixa.find(params[:id])
  end

  # POST /caixas
  # POST /caixas.json
  def create
    @caixa = Caixa.new(params[:caixa])

    respond_to do |format|
      if @caixa.save
        format.html { redirect_to @caixa, notice: 'Caixa was successfully created.' }
        format.json { render json: @caixa, status: :created, location: @caixa }
      else
        format.html { render action: "new" }
        format.json { render json: @caixa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /caixas/1
  # PUT /caixas/1.json
  def update
    @caixa = Caixa.find(params[:id])

    respond_to do |format|
      if @caixa.update_attributes(params[:caixa])
        format.html { redirect_to @caixa, notice: 'Caixa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @caixa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caixas/1
  # DELETE /caixas/1.json
  def destroy
    @caixa = Caixa.find(params[:id])
    @caixa.destroy

    respond_to do |format|
      format.html { redirect_to caixas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/crud.rb
module Crud
	
	def initialize
		super
		@modelo        = self.class.name.gsub('Controller','').underscore.singularize.camelcase.constantize unless @modelo
		@nome_singular = @modelo.to_s.underscore
		@nome_plural   = @modelo.to_s.underscore.pluralize
	end
	
	def index
		set(@nome_plural,@modelo.order('updated_at DESC'))
	end
	
	def show
		busca_registro()
	end
	
	def new
		novo_registro()		
	end
	
	def create
		novo_registro(params[@nome_singular.to_sym])
		
		if @registro.save
			redirect_to(@registro)
		else
			render(action: :new)
		end
	end
	
	def edit
		busca_registro()
	end
	
	def update
		busca_registro()
		
		if @registro.update_attributes(params[@nome_singular.to_sym])
			redirect_to(@registro)
		else
			render(action: :edit)
		end
	end
	
	def destroy
		busca_registro()
		
		@registro.destroy
		
		redirect_to(action: :index)
	end
	
	protected
	
	def busca_registro
		set(@nome_singular,@modelo.find(params[:id]))
		@registro = get(@nome_singular)
	end
	
	def novo_registro(atributos={})
		set(@nome_singular,@modelo.new(atributos))
		@registro = get(@nome_singular)
	end
	
	def set(nome,valor)
		instance_variable_set("@#{nome}",valor)
	end
	
	def get(nome)
		instance_variable_get("@#{nome}")
	end
end

app/controllers/transacoes_controller.rb
class TransacoesController < ApplicationController
	include Crud
	
	def index
		@caixas = Caixa.all
		@transacoes = Transacao.order(:data)
		@pisca = Transacao.find(params[:pisca]) if params[:pisca]
	end
	
	def new
		super 
		
		if params[:transacao]
			@transacao.caixa_id = params[:transacao][:caixa_id]
			@transacao.valor = params[:transacao][:valor].to_f
		end
	end
	
	def update
		busca_registro()
		
		if @registro.update_attributes(params[@nome_singular.to_sym])
			cria_repeticoes()
			redirect_to(transacoes_path(caixa: @transacao.caixa_id, pisca: @transacao.id))
		else
			render(action: :edit)
		end
	end
	
	def create
		@transacao = Transacao.new(params[:transacao])
		
		if @transacao.save
			cria_repeticoes()
			redirect_to(transacoes_path(caixa: @transacao.caixa_id, pisca: @transacao.id))
		else
			render(action: :edit)
		end
	end
	
	private
	
	def cria_repeticoes
		if params[:repetir] && !params[:repetir][:proximos_meses].to_i.zero?
			params[:repetir][:proximos_meses].to_i.times do |i|
				trn = Transacao.new(params[:transacao])
				trn.data = trn.data + (i + 1).month
				trn.save!
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caixas_helper.rb
module CaixasHelper
end

app/helpers/filtra_html_helper.rb
module FiltraHtmlHelper
	
	# Este helper cria um input para filtrar elementos html na tela.
	# 
	# *seletor*: É o seletor CSS utilizado para encontrar os elementos no html;
	# *options*: Qualquer outra propriedade opcao html que ache necessária.
	# *options[:watermark]*: Adiciona um watermark no input;
	# 
	# Exemplo:
	# 	filtra_html('div.indice div.item', style: 'width: 500px; background:red;')
	def filtra_html(seletor, options)
		
		options.reverse_merge!({ id: 'filtra_html'})
		
		options.merge!({ class: 'filtra_html', autocomplete: 'off',
			onkeyup: " $('#{seletor}').hide(); $('#{seletor}:containsI(\"'+$(this).val()+'\")').show(); #{options[:onkeyup]}" })
		
		watermark = options[:watermark] ? javascript_tag("$('##{options[:id]}').watermark('#{options[:watermark]}');") : ''
		
		text_field_tag(options[:id],'',options) + watermark
	end
end

app/helpers/flecha_esconde_informacao_helper.rb
module FlechaEscondeInformacaoHelper

	def flecha_esconde_informacao(seletor,params)

		params.reverse_merge!({
			id: 'controle_flecha_esconde_informacao',
			expande_id: 'expande',
			recolhe_id: 'recolhe',
			ao_expandir: '',
			ao_recolher: ''
		})
		
		render(partial: "layouts/flecha_esconde_informacao", locals: {seletor: seletor, params: params})
		
		end
	end

app/helpers/transacoes_helper.rb
module TransacoesHelper
	def colore_valor(valor)
		"<font color='#{valor < 0 ? :red : :blue}'>#{valor.reais}</font>".html_safe
	end
end

app/views/caixas/_form.html.erb
<%= form_for(@caixa) do |f| %>
  <% if @caixa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@caixa.errors.count, "error") %> prohibited this caixa from being saved:</h2>

      <ul>
      <% @caixa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/caixas/edit.html.erb
<h1>Editing caixa</h1>

<%= render 'form' %>

<%= link_to 'Show', @caixa %> |
<%= link_to 'Back', caixas_path %>

app/views/caixas/index.html.erb
<h1>Caixas</h1>

<%= link_to 'Novo Caixa', new_caixa_path %>

<br />

<table>
	<tr>
		<th>Nome</th>
		<th>Saldo</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

	<% @caixas.each do |caixa| %>
	<tr>
		<td><%= caixa.nome %></td>
		<td><%= caixa.saldo %></td>
		<td><%= link_to 'Exibe', caixa %></td>
		<td><%= link_to 'Edita', edit_caixa_path(caixa) %></td>
		<td><%= link_to 'Deleta', caixa, confirm: 'Are you sure?', method: :delete %></td>
	</tr>
	<% end %>
</table>

<br />

<%= link_to 'Novo Caixa', new_caixa_path %>

app/views/caixas/new.html.erb
<h1>New caixa</h1>

<%= render 'form' %>

<%= link_to 'Back', caixas_path %>

app/views/caixas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @caixa.nome %>
</p>


<%= link_to 'Edit', edit_caixa_path(@caixa) %> |
<%= link_to 'Back', caixas_path %>

app/views/layouts/_flecha_esconde_informacao.html.erb
<div id="<%= params[:id] %>" class='flecha_esconde_informacao'>
	
	<%= image_tag('seta_informacao_recolhida.png', class: params[:expande_id],
		onclick: "$('#{seletor}').show(); $(this).hide(); $('div##{params[:id]} img.#{params[:recolhe_id]}').show(); 
		#{params[:ao_expandir]};") %>
		
	<%= image_tag('seta_informacao_expandida.png', class: params[:recolhe_id], style: "display:none",
		onclick: "$('#{seletor}').hide(); $(this).hide(); $('div##{params[:id]} img.#{params[:expande_id]}').show(); 
		#{params[:ao_expandir]};") %>

</div>

app/views/layouts/_menu.html.erb
<ul>
	<li class='<%= controller.controller_name == 'transacoes' ? 'ativo' : '' %>'><%= link_to('Transações', transacoes_path) %></li>
	<li class='<%= controller.controller_name == 'caixas' ? 'ativo' : '' %>'><%= link_to('Caixas', caixas_path) %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Tesoureiro</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	
	<body controller='<%= controller.controller_name %>' action='<%= controller.action_name %>'>
		
		<nav id="menu">
			<%= render('layouts/menu') %>
		</nav>
		
		<div id="conteudo">
			<%= yield %>
		</div>
		
		<div id="direita">
		</div>
	</body>
</html>

app/views/transacoes/_aba_caixa.html.erb
<div class="aba_caixa" id="<%= c.id %>">
	<%= render(partial: "bater_caixa", locals: {c: c}) %>
	<div><%= link_to('Nova transação', new_transacao_path(transacao: {caixa_id: c.id})) %></div>
	<%= render(partial: 'tabela_transacoes', locals:{c: c}) %>
</div>

app/views/transacoes/_bater_caixa.html.erb
<div id="bater_caixa_<%= c.id %>" saldo_atual='<%= c.saldo %>'>
	<b>Saldo Atual:</b> <%= colore_valor c.saldo %>
	<b>Tenho: </b> <%= text_field_tag('tenho','', onkeyup: "TRNs.exibeResultadoCaixa(#{c.id})") %>
	<b>Falta Lançar: </b>
	<div id="resultado" style="display: inline-block">
		
	</div>
	<div id="link_base" style="display:none">		
	<%= link_to('resultado',new_transacao_path(transacao:{caixa_id: c.id, valor: 'resultado'})) %>
	</div>
</div>

app/views/transacoes/_form.html.erb
<%= form_for(@transacao) do |f| %>
	<% if @transacao.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@transacao.errors.count, "erro") %>:</h2>
			<ul>
				<% @transacao.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :caixa_id %>
		<%= f.select :caixa_id , Caixa.all.map{|c| [c.nome, c.id]} %>
	</div>
	<div class="field">
		<%= f.label :descricao, 'Descrição' %><br>
		<%= f.text_field :descricao , size: 45 %>
	</div>
	<div class="field">
		<%= f.label :data %>
		<%= f.date_select :data %>
	</div>
	<div class="field">
		<%= f.label :valor %><br>
		<%= f.text_field :valor %>
	</div>
	<div class="field">
		<%= f.check_box :realizada %>
		<%= f.label :realizada, 'Realizada?' %>
	</div>
	<div class="field">
		<%= label :repetir, 'Repetir para os próximos' %>
		<%= text_field :repetir, :proximos_meses, size: 2, value: 0 %>
		<%= label :meses, 'meses' %>
	</div>
	
	<div class="actions"><%= f.submit %></div>
	<br>
<% end %>

app/views/transacoes/_inicio_mes.html.erb
<tr class='inicio_mes'>
	<td colspan='6' align='left'>
		<%= flecha_esconde_informacao("table.transacoes[caixa=#{c.id}] tr.transacao[mes_ano=\"#{mes_ano}\"]", 
			id: "caixa_#{c.id}_esconde_mes_#{mes_ano.gsub('/','')}",
			ao_expandir: "var t = $('table.transacoes[caixa=#{c.id}]'); t.find('tr.transacao[mes_ano=\"#{mes_ano}\"]').attr('visivel', true);",
			ao_recolher: "var t = $('table.transacoes[caixa=#{c.id}]'); t.find('tr.transacao[mes_ano=\"#{mes_ano}\"]').attr('visivel', false);") %>
		<%= mes_ano %>
	</td>
	<td id='saldo_realizado' align='right'><%= colore_valor @realizado %></td>
	<td id='saldo_previsto' align='right'><%= colore_valor @previsto %></td>
</tr>

app/views/transacoes/_linha_transacao.html.erb
<% @realizado += t.valor if t.realizada?  %>
<% @previsto += t.valor %>

<tr id='<%= t.id %>' class='transacao <%= t.realizada? ? 'realizada' : 'prevista' %>' mes_ano='<%= mes_ano %>' visivel='false'>
	<td class='acao'><%= link_to(image_tag('edit.png'),edit_transacao_path(t)) %></td>
	<td class='acao'><%= link_to(image_tag('delete.png'), t, method: :delete, confirm: 'Tem Certeza?') %></td>
	<td class='acao'><%= check_box_tag(:trn, :realizada, t.realizada, disabled: true, title: "Transação #{t.realizada ? :realizada : :prevista}" ) %></td>
	<td id='data' ><%= t.data.to_s_br %></td>
	<td id='descricao' ><%= t.descricao %></td>
	<td id='valor' align='right'><%= colore_valor t.valor %></td>
	<td id='saldo_realizado' align='right'><%= colore_valor @realizado %></td>
	<td id='saldo_previsto' align='right'><%= colore_valor @previsto %></td>
</tr>

app/views/transacoes/_tabela_transacoes.html.erb
<table class="transacoes" caixa=<%= c.id %>>
	<thead>
		<tr>
			<th colspan='3'></th>
			<th id='data'  align='left'>Data</th>
			<th id='descricao' >Descrição</th>
			<th id='valor'  align='right'>Valor</th>
			<th id='saldo_realizado' align='right' rowspan=2>Saldo<br>Realizado</th>
			<th id='saldo_previsto'  align='right' rowspan=2>Saldo<br>Previsto</th>
		</tr>
		<tr>
			
			<td>
				<%= image_tag('seta_informacao_recolhida.png', class: "expande_todos_meses", style: 'width: 11px; height:11px; cursor: pointer;',               onclick: "$(this).hide(); $('table.transacoes[caixa=#{c.id}] img.recolhe_todos_meses').show(); $('table.transacoes[caixa=#{c.id}] div.flecha_esconde_informacao img.expande').click();") %>
				<%= image_tag('seta_informacao_expandida.png', class: "recolhe_todos_meses", style: 'width: 11px; height:11px; cursor: pointer; display:none;', onclick: "$(this).hide(); $('table.transacoes[caixa=#{c.id}] img.expande_todos_meses').show(); $('table.transacoes[caixa=#{c.id}] div.flecha_esconde_informacao img.recolhe').click();") %>
			</td>
			
			<td colspan='5'>
				<%= filtra_html('table.transacoes[caixa=#c.id] tr.transacao[visivel=true]',{ id: "pesquisar_caixa_#{c.id}",
					style: 'width: 100%', watermark: 'Pesquise...'}) %>
			</td>
		</tr>
	</thead>
	
	<tbody>
		
		<% @previsto=0.00; @realizado=0.00 %>
		
		<% c.transacoes.order(:data).group_by(&:mes_ano).each do |mes_ano, trns| %>
			<%= render(partial: "inicio_mes", locals:{c: c, mes_ano: mes_ano}) %>
			<%= render(partial: 'linha_transacao', collection: trns, as: :t, locals:{mes_ano: mes_ano}) %>
		<% end %>
		
	</tbody>
</table>

app/views/transacoes/edit.html.erb
<h1>Editando transação</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @transacao %> |
<%= link_to 'Voltar', transacoes_path(caixa: @transacao.caixa) %>

app/views/transacoes/index.html.erb
<h1 align='center'> Transações </h1>

<ul class='abas_caixas'>
	<% @caixas.each do |c| %>
		<li id='<%= c.id %>'><%= link_to_function(c.nome, "TRNs.selecionaCaixa(#{c.id})") %></li>
	<% end %>
</ul>

<%= render(partial: 'aba_caixa', collection: @caixas, as: 'c') %>

<script type="text/javascript" charset="utf-8">
<% caixa = params[:caixa] || @caixas.first.id %>

	TRNs.selecionaCaixa(<%= caixa %>);
	
	$('#caixa_<%= caixa %>_esconde_mes_<%= Date.today.to_s(:mes_ano).gsub('/', '') %> img.expande').click()

	<% if @pisca %>
			$('#caixa_<%= caixa %>_esconde_mes_<%= @pisca.data.to_s(:mes_ano).gsub('/', '') %> img.expande').click()
			TRNs.pisca(<%= @pisca.id %>);
	<% end %>
</script>

app/views/transacoes/new.html.erb
<h1>Nova transação</h1>

<%= render 'form' %>

<%= link_to 'Voltar', transacoes_path(caixa: @transacao.caixa) %>